taco:
  order:
    pageSize: 15 # Spring allows for variations in property names, so it does not matter if we use page-size, or pageSize
server:
  port: 8443
  ssl: # Generate using keytool in the terminal
    key-store: mykeys.jks
    key-store-password: ${SSL_KEY_PASSWORD}
    key-password: ${SSL_KEY_PASSWORD}
logging:
  file.name: logs/TacoCloud.log
spring:
  data:
    rest:
      base-path: /data-api
  security:
     oauth2:
        resourceserver:
           jwt:
              jwk-set-uri: http://localhost:9000/oauth2/jwks
